### PR TITLE
add gulp

### PR DESCRIPTION
**Pull request by talgautb**
Hi @alvarotrigo 
I added `gulp` to compress js.

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for it!

**Comment by talgautb** [comment]
just complied version in `dist` directory ?

**Comment by talgautb** [comment]
@alvarotrigo delete complied version from root folder?

**Comment by alvarotrigo** [comment]
> just complied version in dist directory ?

Yep, such as in [fullPage.js](https://github.com/alvarotrigo/fullPage.js).

> @alvarotrigo delete complied version from root folder?

No deletions.

**Comment by talgautb** [comment]
@alvarotrigo Done ;-)

**Comment by alvarotrigo** [comment]
Thanks for it!

**Pull request merged**
