### PR TITLE
Add scrollDelay to options

### LINKED ISSUE #107: "scrollDelay" is not included in the options
The `scrollDelay` variable which defines the delay to take place before being able to scroll to the next section is currently not available in the options.

### PR DESCRIPTION
**Pull request by abhijitparida**
Fixes #107

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for that! 
But I won't add the option and will very probably deal to unwanted results.

**Comment by abhijitparida** [comment]
What about adding it with a big red warning? We can have it fallback to the default 600 value if the user is on an Apple device.

Something like
```
var kineticScrollDevice = navigator.userAgent.match(/(Mac|iPhone|iPod|iPad)/);
```

**Comment by alvarotrigo** [comment]
I prefer to go for the fullPage.js option ;)

**Comment by abhijitparida** [comment]
Alright then! :)

**Comment by alvarotrigo** [comment]
If you fancy to experiment a bit more, you could even try the [Lethargy library](https://github.com/d4nyll/lethargy)

**Pull request closed without merging**
