### PR TITLE
add navigation classes

### PR DESCRIPTION
**Pull request by talgautb**
Now we can use classes for navigation (1 or more for item), default there are no classes.
it is comfortably for using css methodology like bem

### CODE REVIEW

**Comment by talgautb** [comment]
@alvarotrigo :(

**Comment by alvarotrigo** [comment]
Sorry I forgot about this topic.

I believe it is a better approach to use prefixed classes for the parent element like it is now.
The list wrapper is using `id="multiscroll-nav"` and that should be enough. 

I don't see why would you want to add a class for each element. No need for it.

**Comment by talgautb** [comment]
@alvarotrigo we use bem, so we don't want to use tag without class or with id :)
but thx for looked

**Comment by alvarotrigo** [comment]
@talgautb I don't know what Bem is, but it should be able to deal with tags without classes.

**Pull request closed without merging**
